# This travis configuration file is part of SCHISM
#
# @copyright (C) 2021 Helmholtz-Zentrum Geesthacht
# @author Carsten Lemmen, Helmholtz-Zentrum Geesthacht
#

language: c # There is no Fortran support yet in travis, so we emulate it

dist: focal
git:
  depth: 1

branches:
  only: [ travis-ci master ]

cache:
  - brew: true
  - pip: true
  - apt: true

addons:

  # A list of trusty packages is provided at https://packages.ubuntu.com/trusty/allpackages?format=txt.gz
  apt:
    packages:
      - gfortran
      - libopenmpi-dev
      - libnetcdff5
      - libnetcdf-dev
      - libnetcdfc7
      - netcdf-bin
      #- libmpich-dev
      #
  brew:
    - gfortran
    - open-mpi
    - netcdf

os:
  - linux
  - osx

osx_image: xcode12.2

notifications:
  email: true

env:
  - global:
    - SCHISM_DIR=${TRAVIS_BUILD_DIR}/platipodium/schism
    - SCHISM_BUILD_DIR=${TRAVIS_BUILD_DIR}/build
    - MAKEFLAGS="-j 4"

before_install:
  - mkdir -p ${SCHISM_BUILD_DIR}
  - echo $(nf-config --all)
  - echo $(mpifort --version)

install:
  - cd ${SCHISM_BUILD_DIR}
  - cmake ${SCHISM_DIR}/src
  - make pschism

before_script:

script:

after_success:
  # - cd $TRAVIS_BUILD_DIR
  # - git config --global user.name "TRAVIS-CI-for-$(git --no-pager show -s --format='%cn' $TRAVIS_COMMIT)"
  # - git config --global user.email "$(git --no-pager show -s --format='%ce' $TRAVIS_COMMIT)"
