# This travis configuration file is part of SCHISM
#
# @copyright (C) 2021 Helmholtz-Zentrum Geesthacht
# @author Carsten Lemmen, Helmholtz-Zentrum Geesthacht
#

language: c # There is no Fortran support yet in travis, so we emulate it

os: [ linux osx ]

osx_image: xcode12.2
dist: focal

git:
  depth: 1

branches:
  only: [ travis-ci master ]

cache:
  - brew: true
  - pip: true
  - apt: true

notifications:
  email: true

env:
  - global:
    - SCHISM_DIR=${TRAVIS_BUILD_DIR}
    - SCHISM_BUILD_DIR=${TRAVIS_BUILD_DIR}/../build
    - MAKEFLAGS="-j 4"

addons:
  apt:
    packages:
      - gfortran
      - libopenmpi-dev
      - libnetcdff5
      - libnetcdf-dev
      - libnetcdfc7
      - netcdf-bin
      #- libmpich-dev
      #
  brew:
    - gfortran
    - open-mpi
    - netcdf

before_install:
  - echo  ${SCHISM_BUILD_DIR}
  - mkdir -p ${SCHISM_BUILD_DIR}
  - echo $(nc-config --all)
  - echo $(mpicc --version)

install:

before_script:

script:
  - echo ${SCHISM_BUILD_DIR} ${SCHISM_DIR}
  - cd ${SCHISM_BUILD_DIR}
  - cmake ${SCHISM_DIR}/src
  - make pschism

after_success:
  # - cd $TRAVIS_BUILD_DIR
  # - git config --global user.name "TRAVIS-CI-for-$(git --no-pager show -s --format='%cn' $TRAVIS_COMMIT)"
  # - git config --global user.email "$(git --no-pager show -s --format='%ce' $TRAVIS_COMMIT)"
