# This travis configuration file is part of SCHISM
#
# @copyright (C)  2021 Helmholtz-Zentrum Geesthacht
# @author Carsten Lemmen, Helmholtz-Zentrum Geesthacht
#

language: c # There is no Fortran support yet in travis, so we emulate it

dist: trusty
sudo: false
git:
  depth: 1

branches:
  only: travis-ci

cache:
  - brew: true
  - pip: true
  - apt: true

addons:

  # A list of trusty packages is provided at https://packages.ubuntu.com/trusty/allpackages?format=txt.gz
  apt:
    packages:
      - gfortran
      #- clang # is provided by default
      - libopenmpi-dev
      - libnetcdff5
      - libnetcdf-dev
      - libnetcdfc7
      - netcdf-bin
      #- libmpich-dev
      #- mpich
      #
  brew:
    - gfortran
    - open-mpi
    - netcdf

os:
  - linux
  - osx

#osx_image: xcode9.3beta

before_install:
  # - brew update
  # - brew install netcdf
  # - brew install json-fortran
  # - brew install doxygen

notifications:
  email: true

env:
  - global:

install:
  - cd $TRAVIS_BUILD_DIR
  - cmake  ../src/
  - make pschism 

before_script:

script:

after_success:
  # - cd $TRAVIS_BUILD_DIR
  # - git config --global user.name "TRAVIS-CI-for-$(git --no-pager show -s --format='%cn' $TRAVIS_COMMIT)"
  # - git config --global user.email "$(git --no-pager show -s --format='%ce' $TRAVIS_COMMIT)"
